version: "3.9"

services:
  user-springboot-docker-compose-app-container:
    image: mhbappy18/eureka
    container_name: eureka
    ports:
      - "8761:8080"
    volumes:
      - ./application:/tmp/springboot-docker-compose-app
    networks:
      - backend

